### ISSUE TITLE
Crashing with {:error, :emfile} errors

### ISSUE THREAD

**Issue by Zensavona** [adamkittelson/dogstatsd-elixir#6]
Hi, 
I'm not even sure if this is related to this library directly, but I figured I'd ask.

In production I have ~200 workers who all report stats with this library, they're crawling web pages and reporting things like times to process a piece of data (with timers) and adding to histograms.

I've been getting some application crashes with crash reports like these:

```elixir
2017-04-16 06:04:12.254 [error] Task #PID<0.3552.0> started from :url_supervisor_3 terminating
** (MatchError) no match of right hand side value: {:error, :emfile}
    (dogstatsd) lib/dogstatsd.ex:3: DogStatsd.send_to_socket/2
    (store) lib/url_store.ex:21: anonymous fn/2 in Store.ToCrawl.push/2
    (stdlib) timer.erl:197: :timer.tc/3
    (store) lib/url_store.ex:18: Store.ToCrawl.push/2
    (workers) lib/url.ex:23: anonymous fn/0 in Workers.Url.worker/0
    (stdlib) timer.erl:197: :timer.tc/3
    (workers) lib/url.ex:6: Workers.Url.worker/0
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
Function: &Workers.Url.worker/0
    Args: []
```

```elixir
=CRASH REPORT==== 16-Apr-2017::06:04:12 ===
  crasher:
    initial call: Elixir.Workers.Url:worker/0
    pid: <0.3552.0>
    registered_name: []
    exception exit: {{badmatch,{error,emfile}},
                     [{'Elixir.DogStatsd',send_to_socket,2,
                          [{file,"lib/dogstatsd.ex"},{line,3}]},
                      {'Elixir.Store.ToCrawl','-push/2-fun-4-',2,
                          [{file,"lib/url_store.ex"},{line,21}]},
                      {timer,tc,3,[{file,"timer.erl"},{line,197}]},
                      {'Elixir.Store.ToCrawl',push,2,
                          [{file,"lib/url_store.ex"},{line,18}]},
                      {'Elixir.Workers.Url','-worker/0-fun-1-',0,
                          [{file,"lib/url.ex"},{line,23}]},
                      {timer,tc,3,[{file,"timer.erl"},{line,197}]},
                      {'Elixir.Workers.Url',worker,0,
                          [{file,"lib/url.ex"},{line,6}]},
                      {'Elixir.Task.Supervised',do_apply,2,
                          [{file,"lib/task/supervised.ex"},{line,85}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 116)
    ancestors: [url_supervisor_3,'Elixir.Workers.Supervisor',<0.2306.0>]
    messages: []
    links: [<0.2312.0>]
    dictionary: [{rand_seed,{#{max => 288230376151711743,
                                next => #Fun<rand.8.41921595>,type => exsplus,
                                uniform => #Fun<rand.9.41921595>,
                                uniform_n => #Fun<rand.10.41921595>},
                              [125500113547063606|170501913836768600]}}]
    trap_exit: false
    status: running
    heap_size: 10958
    stack_size: 27
    reductions: 185414
  neighbours:
```

These errors seem to come from all the parts of the codebase which use `dogstatsd`, and my understanding is that emfile errors are to do with having too many files open on the OS (?), FWIW I am using Ubuntu 16.04 on a pretty big VM (10 cores, 64GB). I've never seen this kind of crash on my local dev machine, although it also reports stats. It's a little smaller and perhaps never manages to cycle fast enough to cause the issue?

My question I guess is: do you have any ideas as to how I can debug this further? I am guessing this is because `dogstatsd` is getting overwhelmed. Any ideas on how to prevent this?

Thanks!

**Comment by adamkittelson** [comment]
It sounds like it would be related to the max file descriptors limit configured on your machine. (either max per process (since the erlang vm is just one process), max for your user, or max for your machine). In some setups it defaults to as low as 1024.

I'd recommend doing some digging to see what yours is set at and look into increasing it. This is one of the things that the phoenix team ran into when they were working on getting to two million connections on a single machine http://www.phoenixframework.org/blog/the-road-to-2-million-websocket-connections. You can probably find how to see what yours is set at and how to raise it by googling things around max file descriptors / max open files on your version of ubuntu.

I'm going to close this for now but feel free to re-open if that turns out not to be the issue.

Thanks for reporting!

Adam
